### ISSUE TITLE
When creating an alert Cancel button does not clear the map.

### ISSUE THREAD

**Issue by navish** [CodeTanzania/emis-web-alert#40]

**Comment by navish** [comment]
![issue-no-40](https://user-images.githubusercontent.com/8484784/48802324-009fa900-ed20-11e8-8e03-cb47367b63b2.JPG)

The image shows what happens when I cancel the create new alert action.  I cancelled the action by clicking the X on the top right corner of the form since the cancel button does not work.

**Comment by Mloweedgar** [comment]
Yes, I see. I will work on it. thank you for your comments
